# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'rtt2uart_updated.ui'
##
## Created by: Qt User Interface Compiler version 6.9.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QCheckBox, QComboBox, QDialog,
    QFrame, QGroupBox, QLabel, QLineEdit,
    QPushButton, QRadioButton, QSizePolicy, QWidget)

class Ui_ConnectionDialog(object):
    def setupUi(self, ConnectionDialog):
        if not ConnectionDialog.objectName():
            ConnectionDialog.setObjectName(u"ConnectionDialog")
        ConnectionDialog.setWindowModality(Qt.WindowModality.NonModal)
        ConnectionDialog.resize(401, 545)
        sizePolicy = QSizePolicy(QSizePolicy.Policy.Fixed, QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(ConnectionDialog.sizePolicy().hasHeightForWidth())
        ConnectionDialog.setSizePolicy(sizePolicy)
        ConnectionDialog.setMinimumSize(QSize(401, 545))
        ConnectionDialog.setMaximumSize(QSize(401, 545))
        ConnectionDialog.setSizeGripEnabled(False)
        self.pushButton_Start = QPushButton(ConnectionDialog)
        self.pushButton_Start.setObjectName(u"pushButton_Start")
        self.pushButton_Start.setGeometry(QRect(100, 500, 181, 41))
        font = QFont()
        font.setFamilies([u"\u5fae\u8f6f\u96c5\u9ed1"])
        font.setPointSize(13)
        font.setBold(True)
        font.setUnderline(False)
        font.setStrikeOut(False)
        self.pushButton_Start.setFont(font)
        self.pushButton_Start.setCheckable(True)
        self.pushButton_Start.setAutoRepeat(True)
        self.pushButton_Start.setAutoDefault(True)
        self.line = QFrame(ConnectionDialog)
        self.line.setObjectName(u"line")
        self.line.setEnabled(True)
        self.line.setGeometry(QRect(10, 225, 381, 16))
        self.line.setFrameShape(QFrame.Shape.HLine)
        self.line.setFrameShadow(QFrame.Shadow.Sunken)
        self.groupBox = QGroupBox(ConnectionDialog)
        self.groupBox.setObjectName(u"groupBox")
        self.groupBox.setGeometry(QRect(10, 150, 381, 51))
        self.comboBox_Interface = QComboBox(self.groupBox)
        self.comboBox_Interface.setObjectName(u"comboBox_Interface")
        self.comboBox_Interface.setGeometry(QRect(10, 20, 241, 22))
        self.comboBox_Speed = QComboBox(self.groupBox)
        self.comboBox_Speed.setObjectName(u"comboBox_Speed")
        self.comboBox_Speed.setGeometry(QRect(260, 20, 111, 22))
        self.groupBox_2 = QGroupBox(ConnectionDialog)
        self.groupBox_2.setObjectName(u"groupBox_2")
        self.groupBox_2.setGeometry(QRect(10, 90, 381, 51))
        self.comboBox_Device = QComboBox(self.groupBox_2)
        self.comboBox_Device.setObjectName(u"comboBox_Device")
        self.comboBox_Device.setGeometry(QRect(10, 20, 321, 22))
        self.pushButton_Selete_Device = QPushButton(self.groupBox_2)
        self.pushButton_Selete_Device.setObjectName(u"pushButton_Selete_Device")
        self.pushButton_Selete_Device.setGeometry(QRect(340, 20, 31, 23))
        self.groupBox_UART = QGroupBox(ConnectionDialog)
        self.groupBox_UART.setObjectName(u"groupBox_UART")
        self.groupBox_UART.setGeometry(QRect(10, 328, 381, 81))
        self.comboBox_Port = QComboBox(self.groupBox_UART)
        self.comboBox_Port.setObjectName(u"comboBox_Port")
        self.comboBox_Port.setGeometry(QRect(80, 20, 221, 22))
        self.label = QLabel(self.groupBox_UART)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(13, 20, 61, 20))
        self.label_2 = QLabel(self.groupBox_UART)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(13, 48, 61, 21))
        self.comboBox_baudrate = QComboBox(self.groupBox_UART)
        self.comboBox_baudrate.setObjectName(u"comboBox_baudrate")
        self.comboBox_baudrate.setGeometry(QRect(80, 48, 221, 22))
        self.pushButton_scan = QPushButton(self.groupBox_UART)
        self.pushButton_scan.setObjectName(u"pushButton_scan")
        self.pushButton_scan.setGeometry(QRect(310, 20, 61, 23))
        self.checkBox_resettarget = QCheckBox(ConnectionDialog)
        self.checkBox_resettarget.setObjectName(u"checkBox_resettarget")
        self.checkBox_resettarget.setGeometry(QRect(20, 210, 91, 20))
        self.checkBox_log_split = QCheckBox(ConnectionDialog)
        self.checkBox_log_split.setObjectName(u"checkBox_log_split")
        self.checkBox_log_split.setGeometry(QRect(120, 210, 80, 20))
        self.checkBox_log_split.setChecked(True)
        self.groupBox_RTTControlBlock = QGroupBox(ConnectionDialog)
        self.groupBox_RTTControlBlock.setObjectName(u"groupBox_RTTControlBlock")
        self.groupBox_RTTControlBlock.setGeometry(QRect(10, 240, 381, 80))
        self.radioButton_AutoDetection = QRadioButton(self.groupBox_RTTControlBlock)
        self.radioButton_AutoDetection.setObjectName(u"radioButton_AutoDetection")
        self.radioButton_AutoDetection.setGeometry(QRect(13, 20, 120, 20))
        self.radioButton_AutoDetection.setChecked(True)
        self.radioButton_Address = QRadioButton(self.groupBox_RTTControlBlock)
        self.radioButton_Address.setObjectName(u"radioButton_Address")
        self.radioButton_Address.setGeometry(QRect(150, 20, 80, 20))
        self.radioButton_SearchRange = QRadioButton(self.groupBox_RTTControlBlock)
        self.radioButton_SearchRange.setObjectName(u"radioButton_SearchRange")
        self.radioButton_SearchRange.setGeometry(QRect(260, 20, 111, 20))
        self.lineEdit_RTTAddress = QLineEdit(self.groupBox_RTTControlBlock)
        self.lineEdit_RTTAddress.setObjectName(u"lineEdit_RTTAddress")
        self.lineEdit_RTTAddress.setGeometry(QRect(13, 48, 358, 22))
        self.groupBox_3 = QGroupBox(ConnectionDialog)
        self.groupBox_3.setObjectName(u"groupBox_3")
        self.groupBox_3.setGeometry(QRect(10, 0, 381, 81))
        self.radioButton_usb = QRadioButton(self.groupBox_3)
        self.radioButton_usb.setObjectName(u"radioButton_usb")
        self.radioButton_usb.setGeometry(QRect(10, 20, 89, 20))
        self.radioButton_existing = QRadioButton(self.groupBox_3)
        self.radioButton_existing.setObjectName(u"radioButton_existing")
        self.radioButton_existing.setEnabled(False)
        self.radioButton_existing.setGeometry(QRect(10, 60, 121, 20))
        self.radioButton_tcpip = QRadioButton(self.groupBox_3)
        self.radioButton_tcpip.setObjectName(u"radioButton_tcpip")
        self.radioButton_tcpip.setEnabled(False)
        self.radioButton_tcpip.setGeometry(QRect(10, 40, 89, 20))
        self.checkBox_serialno = QCheckBox(self.groupBox_3)
        self.checkBox_serialno.setObjectName(u"checkBox_serialno")
        self.checkBox_serialno.setGeometry(QRect(150, 20, 81, 20))
        self.comboBox_serialno = QComboBox(self.groupBox_3)
        self.comboBox_serialno.setObjectName(u"comboBox_serialno")
        self.comboBox_serialno.setGeometry(QRect(240, 18, 100, 20))
        self.comboBox_serialno.setEditable(True)
        self.pushButton_refresh_jlink = QPushButton(self.groupBox_3)
        self.pushButton_refresh_jlink.setObjectName(u"pushButton_refresh_jlink")
        self.pushButton_refresh_jlink.setGeometry(QRect(345, 18, 26, 20))
        self.lineEdit_ip = QLineEdit(self.groupBox_3)
        self.lineEdit_ip.setObjectName(u"lineEdit_ip")
        self.lineEdit_ip.setEnabled(False)
        self.lineEdit_ip.setGeometry(QRect(150, 40, 221, 20))
        self.checkBox__auto = QCheckBox(self.groupBox_3)
        self.checkBox__auto.setObjectName(u"checkBox__auto")
        self.checkBox__auto.setEnabled(False)
        self.checkBox__auto.setGeometry(QRect(150, 60, 111, 20))
        self.groupBox_SerialForward = QGroupBox(ConnectionDialog)
        self.groupBox_SerialForward.setObjectName(u"groupBox_SerialForward")
        self.groupBox_SerialForward.setGeometry(QRect(10, 420, 381, 75))
        self.radioButton_LOG = QRadioButton(self.groupBox_SerialForward)
        self.radioButton_LOG.setObjectName(u"radioButton_LOG")
        self.radioButton_LOG.setGeometry(QRect(13, 20, 120, 20))
        self.radioButton_LOG.setChecked(True)
        self.radioButton_DATA = QRadioButton(self.groupBox_SerialForward)
        self.radioButton_DATA.setObjectName(u"radioButton_DATA")
        self.radioButton_DATA.setGeometry(QRect(150, 20, 221, 20))
        self.label_SerialForward = QLabel(self.groupBox_SerialForward)
        self.label_SerialForward.setObjectName(u"label_SerialForward")
        self.label_SerialForward.setGeometry(QRect(13, 45, 61, 20))
        self.comboBox_SerialForward = QComboBox(self.groupBox_SerialForward)
        self.comboBox_SerialForward.setObjectName(u"comboBox_SerialForward")
        self.comboBox_SerialForward.setGeometry(QRect(80, 43, 291, 22))
        self.status = QLabel(ConnectionDialog)
        self.status.setObjectName(u"status")
        self.status.setGeometry(QRect(290, 510, 91, 31))

        self.retranslateUi(ConnectionDialog)

        QMetaObject.connectSlotsByName(ConnectionDialog)
    # setupUi

    def retranslateUi(self, ConnectionDialog):
        ConnectionDialog.setWindowTitle(QCoreApplication.translate("ConnectionDialog", u"RTT2UART Control Panel", None))
        self.pushButton_Start.setText(QCoreApplication.translate("ConnectionDialog", u"Start", None))
        self.groupBox.setTitle(QCoreApplication.translate("ConnectionDialog", u"Target Interface And Speed", None))
        self.comboBox_Speed.setCurrentText("")
        self.groupBox_2.setTitle(QCoreApplication.translate("ConnectionDialog", u"Specify Target Device", None))
        self.pushButton_Selete_Device.setText(QCoreApplication.translate("ConnectionDialog", u"...", None))
        self.groupBox_UART.setTitle(QCoreApplication.translate("ConnectionDialog", u"UART Config", None))
        self.label.setText(QCoreApplication.translate("ConnectionDialog", u"Port:", None))
        self.label_2.setText(QCoreApplication.translate("ConnectionDialog", u"Baud rate:", None))
        self.pushButton_scan.setText(QCoreApplication.translate("ConnectionDialog", u"Scan", None))
        self.checkBox_resettarget.setText(QCoreApplication.translate("ConnectionDialog", u"Reset target", None))
        self.checkBox_log_split.setText(QCoreApplication.translate("ConnectionDialog", u"Log Split", None))
        self.groupBox_RTTControlBlock.setTitle(QCoreApplication.translate("ConnectionDialog", u"RTT Control Block", None))
        self.radioButton_AutoDetection.setText(QCoreApplication.translate("ConnectionDialog", u"Auto Detection", None))
        self.radioButton_Address.setText(QCoreApplication.translate("ConnectionDialog", u"Address", None))
        self.radioButton_SearchRange.setText(QCoreApplication.translate("ConnectionDialog", u"Search Range", None))
#if QT_CONFIG(tooltip)
        self.lineEdit_RTTAddress.setToolTip(QCoreApplication.translate("ConnectionDialog", u"Address example: 0x20000000\n"
"Search Range example: 0x10000000 0x1000, 0x20000000 0x1000", None))
#endif // QT_CONFIG(tooltip)
        self.lineEdit_RTTAddress.setPlaceholderText(QCoreApplication.translate("ConnectionDialog", u"Select a mode above, example will auto-fill", None))
        self.groupBox_3.setTitle(QCoreApplication.translate("ConnectionDialog", u"Connection to J-Link", None))
        self.radioButton_usb.setText(QCoreApplication.translate("ConnectionDialog", u"USB", None))
        self.radioButton_existing.setText(QCoreApplication.translate("ConnectionDialog", u"Existing Session", None))
        self.radioButton_tcpip.setText(QCoreApplication.translate("ConnectionDialog", u"TCP/IP", None))
        self.checkBox_serialno.setText(QCoreApplication.translate("ConnectionDialog", u"Serial NO", None))
        self.pushButton_refresh_jlink.setText(QCoreApplication.translate("ConnectionDialog", u"\u21bb", None))
#if QT_CONFIG(tooltip)
        self.pushButton_refresh_jlink.setToolTip(QCoreApplication.translate("ConnectionDialog", u"Refresh JLink devices", None))
#endif // QT_CONFIG(tooltip)
        self.checkBox__auto.setText(QCoreApplication.translate("ConnectionDialog", u"Auto Reconnect", None))
        self.groupBox_SerialForward.setTitle(QCoreApplication.translate("ConnectionDialog", u"Serial Forward Settings", None))
        self.radioButton_LOG.setText(QCoreApplication.translate("ConnectionDialog", u"LOG Current Tab Selection", None))
        self.radioButton_DATA.setText(QCoreApplication.translate("ConnectionDialog", u"DATA (RTT Channel 1)", None))
        self.label_SerialForward.setText(QCoreApplication.translate("ConnectionDialog", u"Forward Content:", None))
        self.status.setText("")
    # retranslateUi

