# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'rtt2uart.ui'
##
## Created by: Qt User Interface Compiler version 6.6.1
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QCheckBox, QComboBox, QDialog,
    QFrame, QGroupBox, QLabel, QLineEdit,
    QPushButton, QRadioButton, QSizePolicy, QTabWidget,
    QWidget)

class Ui_dialog(object):
    def setupUi(self, dialog):
        if not dialog.objectName():
            dialog.setObjectName(u"dialog")
        dialog.setWindowModality(Qt.NonModal)
        dialog.resize(397, 346)
        dialog.setMinimumSize(QSize(0, 0))
        dialog.setMaximumSize(QSize(2560, 1600))
        dialog.setSizeGripEnabled(False)
        self.pushButton_Start = QPushButton(dialog)
        self.pushButton_Start.setObjectName(u"pushButton_Start")
        self.pushButton_Start.setGeometry(QRect(100, 300, 181, 41))
        font = QFont()
        font.setFamilies([u"\u5fae\u8f6f\u96c5\u9ed1"])
        font.setPointSize(13)
        font.setBold(True)
        font.setUnderline(False)
        font.setStrikeOut(False)
        self.pushButton_Start.setFont(font)
        self.pushButton_Start.setCheckable(True)
        self.pushButton_Start.setAutoRepeat(True)
        self.pushButton_Start.setAutoDefault(True)
        self.line = QFrame(dialog)
        self.line.setObjectName(u"line")
        self.line.setEnabled(True)
        self.line.setGeometry(QRect(10, 225, 381, 16))
        self.line.setFrameShape(QFrame.HLine)
        self.line.setFrameShadow(QFrame.Sunken)
        self.groupBox = QGroupBox(dialog)
        self.groupBox.setObjectName(u"groupBox")
        self.groupBox.setGeometry(QRect(10, 150, 381, 51))
        self.comboBox_Interface = QComboBox(self.groupBox)
        self.comboBox_Interface.setObjectName(u"comboBox_Interface")
        self.comboBox_Interface.setGeometry(QRect(10, 20, 241, 22))
        self.comboBox_Speed = QComboBox(self.groupBox)
        self.comboBox_Speed.setObjectName(u"comboBox_Speed")
        self.comboBox_Speed.setGeometry(QRect(260, 20, 111, 22))
        self.groupBox_2 = QGroupBox(dialog)
        self.groupBox_2.setObjectName(u"groupBox_2")
        self.groupBox_2.setGeometry(QRect(10, 90, 381, 51))
        self.comboBox_Device = QComboBox(self.groupBox_2)
        self.comboBox_Device.setObjectName(u"comboBox_Device")
        self.comboBox_Device.setGeometry(QRect(10, 20, 321, 22))
        self.pushButton_Selete_Device = QPushButton(self.groupBox_2)
        self.pushButton_Selete_Device.setObjectName(u"pushButton_Selete_Device")
        self.pushButton_Selete_Device.setGeometry(QRect(340, 20, 31, 23))
        self.groupBox_UART = QGroupBox(dialog)
        self.groupBox_UART.setObjectName(u"groupBox_UART")
        self.groupBox_UART.setGeometry(QRect(10, 238, 381, 51))
        self.comboBox_Port = QComboBox(self.groupBox_UART)
        self.comboBox_Port.setObjectName(u"comboBox_Port")
        self.comboBox_Port.setGeometry(QRect(50, 20, 81, 22))
        self.label = QLabel(self.groupBox_UART)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(13, 20, 31, 20))
        self.label_2 = QLabel(self.groupBox_UART)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(150, 20, 61, 21))
        self.comboBox_baudrate = QComboBox(self.groupBox_UART)
        self.comboBox_baudrate.setObjectName(u"comboBox_baudrate")
        self.comboBox_baudrate.setGeometry(QRect(218, 20, 71, 22))
        self.pushButton_scan = QPushButton(self.groupBox_UART)
        self.pushButton_scan.setObjectName(u"pushButton_scan")
        self.pushButton_scan.setGeometry(QRect(314, 20, 61, 23))
        self.checkBox_resettarget = QCheckBox(dialog)
        self.checkBox_resettarget.setObjectName(u"checkBox_resettarget")
        self.checkBox_resettarget.setGeometry(QRect(20, 210, 91, 16))
        self.groupBox_3 = QGroupBox(dialog)
        self.groupBox_3.setObjectName(u"groupBox_3")
        self.groupBox_3.setGeometry(QRect(10, 0, 381, 81))
        self.radioButton_usb = QRadioButton(self.groupBox_3)
        self.radioButton_usb.setObjectName(u"radioButton_usb")
        self.radioButton_usb.setGeometry(QRect(10, 20, 89, 16))
        self.radioButton_existing = QRadioButton(self.groupBox_3)
        self.radioButton_existing.setObjectName(u"radioButton_existing")
        self.radioButton_existing.setEnabled(False)
        self.radioButton_existing.setGeometry(QRect(10, 60, 121, 16))
        self.radioButton_tcpip = QRadioButton(self.groupBox_3)
        self.radioButton_tcpip.setObjectName(u"radioButton_tcpip")
        self.radioButton_tcpip.setEnabled(False)
        self.radioButton_tcpip.setGeometry(QRect(10, 40, 89, 16))
        self.checkBox_serialno = QCheckBox(self.groupBox_3)
        self.checkBox_serialno.setObjectName(u"checkBox_serialno")
        self.checkBox_serialno.setGeometry(QRect(150, 20, 81, 16))
        self.lineEdit_serialno = QLineEdit(self.groupBox_3)
        self.lineEdit_serialno.setObjectName(u"lineEdit_serialno")
        self.lineEdit_serialno.setGeometry(QRect(240, 18, 131, 20))
        self.lineEdit_ip = QLineEdit(self.groupBox_3)
        self.lineEdit_ip.setObjectName(u"lineEdit_ip")
        self.lineEdit_ip.setEnabled(False)
        self.lineEdit_ip.setGeometry(QRect(150, 40, 221, 20))
        self.checkBox__auto = QCheckBox(self.groupBox_3)
        self.checkBox__auto.setObjectName(u"checkBox__auto")
        self.checkBox__auto.setEnabled(False)
        self.checkBox__auto.setGeometry(QRect(150, 60, 111, 16))
        self.pushButton = QPushButton(dialog)
        self.pushButton.setObjectName(u"pushButton")
        self.pushButton.setEnabled(False)
        self.pushButton.setGeometry(QRect(940, 310, 75, 31))
        self.cmd_buffer = QComboBox(dialog)
        self.cmd_buffer.addItem("")
        self.cmd_buffer.addItem("")
        self.cmd_buffer.addItem("")
        self.cmd_buffer.addItem("")
        self.cmd_buffer.addItem("")
        self.cmd_buffer.addItem("")
        self.cmd_buffer.addItem("")
        self.cmd_buffer.addItem("")
        self.cmd_buffer.addItem("")
        self.cmd_buffer.addItem("")
        self.cmd_buffer.setObjectName(u"cmd_buffer")
        self.cmd_buffer.setGeometry(QRect(400, 310, 531, 30))
        font1 = QFont()
        font1.setFamilies([u"\u65b0\u5b8b\u4f53"])
        self.cmd_buffer.setFont(font1)
        self.cmd_buffer.setEditable(True)
        self.status = QLabel(dialog)
        self.status.setObjectName(u"status")
        self.status.setGeometry(QRect(290, 300, 91, 31))
        self.tem_switch = QTabWidget(dialog)
        self.tem_switch.setObjectName(u"tem_switch")
        self.tem_switch.setGeometry(QRect(404, 10, 611, 291))

        self.retranslateUi(dialog)

        self.pushButton.setDefault(True)
        self.tem_switch.setCurrentIndex(-1)


        QMetaObject.connectSlotsByName(dialog)
    # setupUi

    def retranslateUi(self, dialog):
        dialog.setWindowTitle(QCoreApplication.translate("dialog", u"RTT2UART Control Panel", None))
        self.pushButton_Start.setText(QCoreApplication.translate("dialog", u"Start", None))
        self.groupBox.setTitle(QCoreApplication.translate("dialog", u"Target Interface And Speed", None))
        self.comboBox_Speed.setCurrentText("")
        self.groupBox_2.setTitle(QCoreApplication.translate("dialog", u"Specify Target Device", None))
        self.pushButton_Selete_Device.setText(QCoreApplication.translate("dialog", u"...", None))
        self.groupBox_UART.setTitle(QCoreApplication.translate("dialog", u"UART Config", None))
        self.label.setText(QCoreApplication.translate("dialog", u"Port:", None))
        self.label_2.setText(QCoreApplication.translate("dialog", u"Baud rate:", None))
        self.pushButton_scan.setText(QCoreApplication.translate("dialog", u"Scan", None))
        self.checkBox_resettarget.setText(QCoreApplication.translate("dialog", u"Reset target", None))
        self.groupBox_3.setTitle(QCoreApplication.translate("dialog", u"Connection to J-Link", None))
        self.radioButton_usb.setText(QCoreApplication.translate("dialog", u"USB", None))
        self.radioButton_existing.setText(QCoreApplication.translate("dialog", u"Existing Session", None))
        self.radioButton_tcpip.setText(QCoreApplication.translate("dialog", u"TCP/IP", None))
        self.checkBox_serialno.setText(QCoreApplication.translate("dialog", u"Serial NO", None))
        self.checkBox__auto.setText(QCoreApplication.translate("dialog", u"Auto Reconnect", None))
        self.pushButton.setText(QCoreApplication.translate("dialog", u"Enter", None))
        self.cmd_buffer.setItemText(0, "")
        self.cmd_buffer.setItemText(1, QCoreApplication.translate("dialog", u"ver?", None))
        self.cmd_buffer.setItemText(2, QCoreApplication.translate("dialog", u"all?", None))
        self.cmd_buffer.setItemText(3, QCoreApplication.translate("dialog", u"tof rf?", None))
        self.cmd_buffer.setItemText(4, QCoreApplication.translate("dialog", u"bf=99,1", None))
        self.cmd_buffer.setItemText(5, QCoreApplication.translate("dialog", u"gsensor=1,1,1,30,5,20#mock gsensor=1,40", None))
        self.cmd_buffer.setItemText(6, QCoreApplication.translate("dialog", u"tof rf=90,8,2,30.5,4,3,0,0,24,0,3,1,120,0,2,3;3,2,1,3,71,65,72;2,30,40,5,20;4,7,2,90,40,3,4,66;", None))
        self.cmd_buffer.setItemText(7, QCoreApplication.translate("dialog", u"prfm=ffff", None))
        self.cmd_buffer.setItemText(8, QCoreApplication.translate("dialog", u"of=1", None))
        self.cmd_buffer.setItemText(9, QCoreApplication.translate("dialog", u"mg=\u4e2d\u6587\u6d4b\u8bd5", None))

        self.status.setText("")
    # retranslateUi

