# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'rtt2uart_updated.ui'
##
## Created by: Qt User Interface Compiler version 6.9.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QCheckBox, QComboBox, QDialog,
    QFrame, QGroupBox, QLabel, QLineEdit,
    QPushButton, QRadioButton, QSizePolicy, QWidget)

class Ui_dialog(object):
    def setupUi(self, dialog):
        if not dialog.objectName():
            dialog.setObjectName(u"dialog")
        dialog.setWindowModality(Qt.WindowModality.NonModal)
        dialog.resize(401, 455)
        sizePolicy = QSizePolicy(QSizePolicy.Policy.Fixed, QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(dialog.sizePolicy().hasHeightForWidth())
        dialog.setSizePolicy(sizePolicy)
        dialog.setMinimumSize(QSize(401, 455))
        dialog.setMaximumSize(QSize(401, 455))
        dialog.setSizeGripEnabled(False)
        self.pushButton_Start = QPushButton(dialog)
        self.pushButton_Start.setObjectName(u"pushButton_Start")
        self.pushButton_Start.setGeometry(QRect(100, 410, 181, 41))
        font = QFont()
        font.setFamilies([u"\u5fae\u8f6f\u96c5\u9ed1"])
        font.setPointSize(13)
        font.setBold(True)
        font.setUnderline(False)
        font.setStrikeOut(False)
        self.pushButton_Start.setFont(font)
        self.pushButton_Start.setCheckable(True)
        self.pushButton_Start.setAutoRepeat(True)
        self.pushButton_Start.setAutoDefault(True)
        self.line = QFrame(dialog)
        self.line.setObjectName(u"line")
        self.line.setEnabled(True)
        self.line.setGeometry(QRect(10, 225, 381, 16))
        self.line.setFrameShape(QFrame.Shape.HLine)
        self.line.setFrameShadow(QFrame.Shadow.Sunken)
        self.groupBox = QGroupBox(dialog)
        self.groupBox.setObjectName(u"groupBox")
        self.groupBox.setGeometry(QRect(10, 150, 381, 51))
        self.comboBox_Interface = QComboBox(self.groupBox)
        self.comboBox_Interface.setObjectName(u"comboBox_Interface")
        self.comboBox_Interface.setGeometry(QRect(10, 20, 241, 22))
        self.comboBox_Speed = QComboBox(self.groupBox)
        self.comboBox_Speed.setObjectName(u"comboBox_Speed")
        self.comboBox_Speed.setGeometry(QRect(260, 20, 111, 22))
        self.groupBox_2 = QGroupBox(dialog)
        self.groupBox_2.setObjectName(u"groupBox_2")
        self.groupBox_2.setGeometry(QRect(10, 90, 381, 51))
        self.comboBox_Device = QComboBox(self.groupBox_2)
        self.comboBox_Device.setObjectName(u"comboBox_Device")
        self.comboBox_Device.setGeometry(QRect(10, 20, 321, 22))
        self.pushButton_Selete_Device = QPushButton(self.groupBox_2)
        self.pushButton_Selete_Device.setObjectName(u"pushButton_Selete_Device")
        self.pushButton_Selete_Device.setGeometry(QRect(340, 20, 31, 23))
        self.groupBox_UART = QGroupBox(dialog)
        self.groupBox_UART.setObjectName(u"groupBox_UART")
        self.groupBox_UART.setGeometry(QRect(10, 238, 381, 81))
        self.comboBox_Port = QComboBox(self.groupBox_UART)
        self.comboBox_Port.setObjectName(u"comboBox_Port")
        self.comboBox_Port.setGeometry(QRect(80, 20, 221, 22))
        self.label = QLabel(self.groupBox_UART)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(13, 20, 61, 20))
        self.label_2 = QLabel(self.groupBox_UART)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(13, 48, 61, 21))
        self.comboBox_baudrate = QComboBox(self.groupBox_UART)
        self.comboBox_baudrate.setObjectName(u"comboBox_baudrate")
        self.comboBox_baudrate.setGeometry(QRect(80, 48, 221, 22))
        self.pushButton_scan = QPushButton(self.groupBox_UART)
        self.pushButton_scan.setObjectName(u"pushButton_scan")
        self.pushButton_scan.setGeometry(QRect(310, 20, 61, 23))
        self.checkBox_resettarget = QCheckBox(dialog)
        self.checkBox_resettarget.setObjectName(u"checkBox_resettarget")
        self.checkBox_resettarget.setGeometry(QRect(20, 210, 91, 20))
        self.checkBox_log_split = QCheckBox(dialog)
        self.checkBox_log_split.setObjectName(u"checkBox_log_split")
        self.checkBox_log_split.setGeometry(QRect(120, 210, 80, 20))
        self.checkBox_log_split.setChecked(True)
        self.groupBox_3 = QGroupBox(dialog)
        self.groupBox_3.setObjectName(u"groupBox_3")
        self.groupBox_3.setGeometry(QRect(10, 0, 381, 81))
        self.radioButton_usb = QRadioButton(self.groupBox_3)
        self.radioButton_usb.setObjectName(u"radioButton_usb")
        self.radioButton_usb.setGeometry(QRect(10, 20, 89, 20))
        self.radioButton_existing = QRadioButton(self.groupBox_3)
        self.radioButton_existing.setObjectName(u"radioButton_existing")
        self.radioButton_existing.setEnabled(False)
        self.radioButton_existing.setGeometry(QRect(10, 60, 121, 20))
        self.radioButton_tcpip = QRadioButton(self.groupBox_3)
        self.radioButton_tcpip.setObjectName(u"radioButton_tcpip")
        self.radioButton_tcpip.setEnabled(False)
        self.radioButton_tcpip.setGeometry(QRect(10, 40, 89, 20))
        self.checkBox_serialno = QCheckBox(self.groupBox_3)
        self.checkBox_serialno.setObjectName(u"checkBox_serialno")
        self.checkBox_serialno.setGeometry(QRect(150, 20, 81, 20))
        self.lineEdit_serialno = QLineEdit(self.groupBox_3)
        self.lineEdit_serialno.setObjectName(u"lineEdit_serialno")
        self.lineEdit_serialno.setGeometry(QRect(240, 18, 131, 20))
        self.lineEdit_ip = QLineEdit(self.groupBox_3)
        self.lineEdit_ip.setObjectName(u"lineEdit_ip")
        self.lineEdit_ip.setEnabled(False)
        self.lineEdit_ip.setGeometry(QRect(150, 40, 221, 20))
        self.checkBox__auto = QCheckBox(self.groupBox_3)
        self.checkBox__auto.setObjectName(u"checkBox__auto")
        self.checkBox__auto.setEnabled(False)
        self.checkBox__auto.setGeometry(QRect(150, 60, 111, 20))
        self.groupBox_SerialForward = QGroupBox(dialog)
        self.groupBox_SerialForward.setObjectName(u"groupBox_SerialForward")
        self.groupBox_SerialForward.setGeometry(QRect(10, 330, 381, 75))
        self.radioButton_LOG = QRadioButton(self.groupBox_SerialForward)
        self.radioButton_LOG.setObjectName(u"radioButton_LOG")
        self.radioButton_LOG.setGeometry(QRect(13, 20, 120, 20))
        self.radioButton_LOG.setChecked(True)
        self.radioButton_DATA = QRadioButton(self.groupBox_SerialForward)
        self.radioButton_DATA.setObjectName(u"radioButton_DATA")
        self.radioButton_DATA.setGeometry(QRect(150, 20, 221, 20))
        self.label_SerialForward = QLabel(self.groupBox_SerialForward)
        self.label_SerialForward.setObjectName(u"label_SerialForward")
        self.label_SerialForward.setGeometry(QRect(13, 45, 61, 20))
        self.comboBox_SerialForward = QComboBox(self.groupBox_SerialForward)
        self.comboBox_SerialForward.setObjectName(u"comboBox_SerialForward")
        self.comboBox_SerialForward.setGeometry(QRect(80, 43, 291, 22))
        self.status = QLabel(dialog)
        self.status.setObjectName(u"status")
        self.status.setGeometry(QRect(290, 420, 91, 31))

        self.retranslateUi(dialog)

        QMetaObject.connectSlotsByName(dialog)
    # setupUi

    def retranslateUi(self, dialog):
        dialog.setWindowTitle(QCoreApplication.translate("dialog", u"RTT2UART Control Panel", None))
        self.pushButton_Start.setText(QCoreApplication.translate("dialog", u"Start", None))
        self.groupBox.setTitle(QCoreApplication.translate("dialog", u"Target Interface And Speed", None))
        self.comboBox_Speed.setCurrentText("")
        self.groupBox_2.setTitle(QCoreApplication.translate("dialog", u"Specify Target Device", None))
        self.pushButton_Selete_Device.setText(QCoreApplication.translate("dialog", u"...", None))
        self.groupBox_UART.setTitle(QCoreApplication.translate("dialog", u"UART Config", None))
        self.label.setText(QCoreApplication.translate("dialog", u"Port:", None))
        self.label_2.setText(QCoreApplication.translate("dialog", u"Baud rate:", None))
        self.pushButton_scan.setText(QCoreApplication.translate("dialog", u"Scan", None))
        self.checkBox_resettarget.setText(QCoreApplication.translate("dialog", u"Reset target", None))
        self.checkBox_log_split.setText(QCoreApplication.translate("dialog", u"Log Split", None))
        self.groupBox_3.setTitle(QCoreApplication.translate("dialog", u"Connection to J-Link", None))
        self.radioButton_usb.setText(QCoreApplication.translate("dialog", u"USB", None))
        self.radioButton_existing.setText(QCoreApplication.translate("dialog", u"Existing Session", None))
        self.radioButton_tcpip.setText(QCoreApplication.translate("dialog", u"TCP/IP", None))
        self.checkBox_serialno.setText(QCoreApplication.translate("dialog", u"Serial NO", None))
        self.checkBox__auto.setText(QCoreApplication.translate("dialog", u"Auto Reconnect", None))
        self.groupBox_SerialForward.setTitle(QCoreApplication.translate("dialog", u"Serial Forward Settings", None))
        self.radioButton_LOG.setText(QCoreApplication.translate("dialog", u"LOG Current Tab Selection", None))
        self.radioButton_DATA.setText(QCoreApplication.translate("dialog", u"DATA (RTT Channel 1)", None))
        self.label_SerialForward.setText(QCoreApplication.translate("dialog", u"Forward Content:", None))
        self.status.setText("")
    # retranslateUi

